import { Store } from './Store';
import type { Telemetry } from './Types';

export const INITIAL_TELEMETRY: Telemetry = {
  armed: false,
  mode: 'angle',
  cameraMode: 'fpv',
  speedKmh: 0,
  verticalSpeed: 0,
  altitude: 0,
  distance: 0,
  batteryPercent: 100,
  voltage: 25.2,
  amps: 0,
  mah: 0,
  throttle: 0,
  rollDeg: 0,
  pitchDeg: 0,
  headingDeg: 0,
  rollRate: 0,
  pitchRate: 0,
  yawRate: 0,
  gForce: 1,
  motors: [0, 0, 0, 0],
  fps: 0,
  flightTime: 0,
  crashed: false,
  crashCount: 0,
  blockedBy: null,
  lap: {
    nextGate: 0,
    totalGates: 0,
    currentLapTime: 0,
    lastLapTime: null,
    bestLapTime: null,
    lapsCompleted: 0,
    running: false,
  },
  linkQuality: 100,
  gateBearing: 0,
  gateElevation: 0,
  gateDistance: 0,
};

export const telemetryStore = new Store<Telemetry>(INITIAL_TELEMETRY);
